# Generated by Django 4.1.1 on 2022-09-29 17:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AliasedUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="Main URL", max_length=300, unique=True),
                ),
                (
                    "alias",
                    models.URLField(
                        default=api.models._generate_non_taken_alias_for_ul,
                        help_text="URL alias for full url path",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
